### PR TITLE
Feature/custom class loaders

### PR DESCRIPTION
**Pull request by mark-gresham**
We are using pf4j as part of our application, but we needed to modify the behaviour of `PluginClassLoader` to verify the classes being loaded. In order to achieve this I introduced a new interface `PluginClassLoaderFactory` which was used as a API extension to select which type of `ClassLoader` to use for a plugin. Our alternate `ClassLoader` uses `PluginClassLoader` as a base.
To ensure that the existing behaviour remains, `DefaultPluginClassLoaderFactory` was implemented.
Altering `ClassLoader`s should probably be considered an _advanced_ use of the framework, something which most users wouldn't need to implement.

### CODE REVIEW

**Comment by decebals** [comment]
Please check #63 (a much simple implementation) to see if satisfy your requirements. Thanks!

**Comment by mark-gresham** [comment]
The changes introduced in #63 look like they could be sufficient for our needs.

**Comment by mark-gresham** [comment]
When could you do a release with #63 and #53 included?

**Comment by decebals** [comment]
See https://github.com/decebals/pf4j/issues/21#issuecomment-129364073. I can release a new version today if the SNAPSHOT is ok for you.

**Comment by mark-gresham** [comment]
Apologies for the delay in replying. We have ran the snapshot code against our codebase and everything is working. If you haven't already done it, could you please do the release?

**Comment by decebals** [comment]
PF4J 0.10.0 released, see https://groups.google.com/forum/#!topic/pf4j/onwDMxheAcA. The new version will be available soon on Maven Central Repository.

**Pull request closed without merging**
